monolit.check.delay-ms=600000
monolit.check.timeout-ms=3000
monolit.vk.long-poll.enabled=true

monolit.reminders.zone=Europe/Moscow

monolit.reminders.meter-reading.cron=0 0 19-22 20-25 * *
monolit.reminders.meter-reading.record.cron=0 0 1 1 * *

monolit.reminders.utility-payment.cron=0 0 19-22 5-10 * *
monolit.reminders.utility-payment.record.cron=0 0 1 1 * *
monolit.reminders.postponed.cron=0 * * * * *
monolit.reminders.custom.cron=* * * * * *

monolit.news.cherinfo.rss-url=https://cherinfo.ru/rss/news/
monolit.news.cherinfo.image.big-path=/image_big/
monolit.news.cherinfo.image.medium-path=/image_medium/
monolit.news.cherinfo.image.small-path=/image_small/
monolit.news.cherinfo.cron=0 0 * * * *

#spring.datasource.url=jdbc:postgresql://192.168.0.16:5432/home_db
spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=postgres
spring.datasource.password=system
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
