monolit.check.delay-ms=60000
monolit.check.timeout-ms=3000
monolit.reminders.zone=Europe/Moscow
monolit.reminders.meter-reading.cron=0 0 8-22 20-25 * *
monolit.reminders.utility-payment.cron=0 0 8-22 5-10 * *
