monolit.check.delay-ms=60000
monolit.check.timeout-ms=3000

monolit.reminders.zone=Europe/Moscow

monolit.reminders.meter-reading.cron=0 0 19-22 20-25 * *
monolit.reminders.meter-reading.record.cron=0 0 1 1 * *

monolit.reminders.utility-payment.cron=0 0 19-22 5-10 * *
monolit.reminders.utility-payment.record.cron=0 0 1 1 * *

spring.datasource.url=jdbc:postgresql://192.168.0.17:5432/home_db
#spring.datasource.url=jdbc:postgresql://localhost:5432/home_db
spring.datasource.username=stik3r
spring.datasource.password=stik3r
spring.datasource.driver-class-name=org.postgresql.Driver
